FROM nginx:alpine

# Copy only the public folder (Nginx only needs static assets)
COPY ./public /var/www/html/public
# Copy our custom Nginx config
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
